from typing import Union, Any, List, BinaryIO, Dict


class IfdTag:
    printable: str = ...
    tag: int = ...
    field_type: int = ...
    field_offset: int = ...
    field_length: int = ...
    values: Union[str, List[Any]]


def process_file(
    f: BinaryIO,
    stop_tag: str = ...,
    details: bool = ...,
    strict: bool = ...,
    debug: bool = ...) -> Dict[str, IfdTag]: ...
